### ISSUE TITLE
Hotstar 

### ISSUE THREAD

**Issue by arjung24** [Clinton-Abraham/COUNTRY-CODES#1]
Is it possible to download hotstar free content via Uploader X bot

**Comment by Clinton-Abraham** [comment]
> Is it possible to download hotstar free content via Uploader X bot

hotstar link only supports in US server bots our https://t.me/uploader_x_bot running in EU server

**Comment by arjung24** [comment]
> > Is it possible to download hotstar free content via Uploader X bot
> 
> hotstar link only supports in US server bots our https://t.me/uploader_x_bot running in EU server

Please make one with US server with Hotstar support.

**Comment by Clinton-Abraham** [comment]
> > > Is it possible to download hotstar free content via Uploader X bot
> > 
> > 
> > hotstar link only supports in US server bots our https://t.me/uploader_x_bot running in EU server
> 
> Please make one with US server with Hotstar support.

I'll try bro...
